### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by rsteinerhh** [AmrMKayid/co-movies#1]
After creating a conda environment and installing the dependencies in requirements.txt I get the following error when executing the script:

Traceback (most recent call last):
  File "/home/rene/anaconda3/envs/co-movies/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/home/rene/anaconda3/envs/co-movies/lib/python3.11/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/home/rene/anaconda3/envs/co-movies/lib/python3.11/site-packages/streamlit/delta_generator.py", line 45, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/home/rene/anaconda3/envs/co-movies/lib/python3.11/site-packages/streamlit/elements/arrow_altair.py", line 35, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

Is there an issue with dependencies or am I missing something?

**Comment by hamaryo** [comment]
@rsteinerhh 
Have you tried the following commands?
`pip install "altair<5" `

altair.vegalite.v4 is the module used in streamlit, but  a version higher than v4 might be installed in your environment. I faced the same error, but in my environment the error was resolved by running this command.
